### ISSUE TITLE
// It's okay to force-unwrap here because we pass a non-empty array.

### ISSUE THREAD

**Issue by nikans** [mischa-hildebrand/AlignedCollectionViewFlowLayout#24] opened 2019-11-06 03:10 UTC
<img width="769" alt="Screenshot 2019-11-06 at 06 08 53" src="https://user-images.githubusercontent.com/1039100/68265079-12c34600-005c-11ea-8368-fdd80a572999.png">

:) 

I had about 1k elements in my collection view, and this is what happened)

**Comment by mischa-hildebrand** [comment] 2019-11-06 13:59
This seems to be the same issue as #7. I haven't been able to reproduce this issue myself. If you'd be able to provide a sample project with this issue it would be very helpful.

(I'll close this issue as a duplicate. Please add any further comments to #7.)

**Closed by mischa-hildebrand** 2019-11-06 13:59 UTC

**Comment by nikans** [comment] 2019-11-22 07:36
Ok @mischa-hildebrand thanks for reviewing this. I use this in production, but I've limited the amount of elements I'm trying to show and haven't encountered this issue since. 
Will post you if detected.
